export const TennisCharities = [
    {
        Id: 1,
        Badge: "Total Sale: $82,571",
        ImageUrl: "/images/tennis1.jpg",
        Edition: 371,
        Stock: 128,
        Title: "KING BITCOIN",
        Price: "$10M",
        Avatar: "/images/tennis2.jpg",
        Author: "newk3d",
        Likes: 652,
      },
      {
        Id: 2,
        Badge: "Total Sale: $82,571",
        ImageUrl: "/images/tennis1.jpg",
        Edition: 371,
        Stock: 128,
        Title: "KING BITCOIN",
        Price: "$10M",
        Avatar: "/images/tennis2.jpg",
        Author: "newk3d",
        Likes: 652,
      },
      {
        Id: 3,
        Badge: "Total Sale: $82,571",
        ImageUrl: "/images/tennis1.jpg",
        Edition: 371,
        Stock: 128,
        Title: "KING BITCOIN",
        Price: "$10M",
        Avatar: "/images/tennis2.jpg",
        Author: "newk3d",
        Likes: 652,
      },
      {
        Id: 4,
        Badge: "Total Sale: $82,571",
        ImageUrl: "/images/tennis1.jpg",
        Edition: 371,
        Stock: 128,
        Title: "KING BITCOIN",
        Price: "$10M",
        Avatar: "/images/tennis2.jpg",
        Author: "newk3d",
        Likes: 652,
      },
      {
        Id: 5,
        Badge: "Total Sale: $82,571",
        ImageUrl: "/images/tennis1.jpg",
        Edition: 371,
        Stock: 128,
        Title: "KING BITCOIN",
        Price: "$10M",
        Avatar: "/images/tennis2.jpg",
        Author: "newk3d",
        Likes: 652,
      },
      {
        Id: 6,
        Badge: "Total Sale: $82,571",
        ImageUrl: "/images/tennis1.jpg",
        Edition: 371,
        Stock: 128,
        Title: "KING BITCOIN",
        Price: "$10M",
        Avatar: "/images/tennis2.jpg",
        Author: "newk3d",
        Likes: 652,
      },
]